location = "West US"
sql_server_version = "12.0"
create_mode = "Default"
collation = "SQL_Latin1_General_CP1_CI_AS"
requested_service_objective_name = "S0"
edition = "basic"
start_ip_address = "0.0.0.0"
end_ip_address = "0.0.0.0"
